# Generated by Django 3.2.8 on 2021-11-07 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_downvote_upvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareKey',
            fields=[
                ('location', models.TextField()),
                ('token', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('expiration_seconds', models.BigIntegerField()),
                ('blog', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sharelink', to='blogs.post')),
            ],
        ),
    ]
